version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 9017:27017
    volumes: 
      - type: bind
        source: /Users/yeonkyu/Desktop/Web/nodejs/data
        target: /data/db
    container_name: "mongodb_server"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9018:8081
    container_name: "mongodb_monitor"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: P@ssw0rd